name: backup

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'

jobs:
  download:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          FILECLOUD_VERSION: ${{github.ref}}
      - name: Install Packages
        run: |
          sudo apt install python3 python3-pip openssl -y
          sudo pip install requests
          sudo mkdir /var/www/openwrt
          sudo chmod 777 -R /var/www/openwrt/
      - name: Run Script
        run: |
          python3 openwrt_mirror.py
      - name: Tar Files
        run: |
          tar -cvf /tmp/packages.tar /var/www/openwrt/
          xz -9 -T 12 -z /tmp/packages.tar
      - name : Upload artifact
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: OpenWrt-xiaomi-AC2100
          path: /tmp/packages.tar.xz
