name: release

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: startsWith(github.ref,'refs/tags/v')
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
        env:
          FILECLOUD_VERSION: ${{github.ref}}
